In [1]:
# Pytorch basics:

In [67]:
import torch 

In [8]:
# Create empty tensors
p = torch.empty(2) # parenthesized no. specifies elements in each dimension.
q = torch.empty(2,3)
r = torch.empty(2,3,5)
print("\n 1D tensor : %s \n 2D tensor: %s \n 3D tensor: %s" %(p,q,r))


 1D tensor : tensor([0., 0.]) 
 2D tensor: tensor([[0., 0., 0.],
        [0., 0., 0.]]) 
 3D tensor: tensor([[[-1.3753e+28,  3.0794e-41,  2.8026e-45,  0.0000e+00,  4.2039e-45],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00, -1.3754e+28,  3.0794e-41, -1.3754e+28]],

        [[ 3.0794e-41, -1.3754e+28,  3.0794e-41,  4.2039e-45,  0.0000e+00],
         [ 1.4013e-45,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]]])


In [22]:
# Generate random numbers & check-change its datatype
a = torch.rand(2,2) # creates a 2D tensor of random numbers
b = torch.rand(2,2).int()
print("\n dtype of a: %s \n dtype of b: %s" %(a.dtype, b.dtype))


 dtype of a: torch.float32 
 dtype of b: torch.int32


In [25]:
# datatypes can also be specified with the tensor
a = torch.ones(3,4, dtype=torch.int)
a.dtype

torch.int32

In [34]:
# Arithmetic operation and inplace operation
a = torch.randint(10,(2,))
b = torch.randint(20,(2,))
c = torch.add(a,b)
print("%s + %s = %s" %(a,b,c))

# using inplace operation to do the same
a.add_(b) # the sum is stored at 'a'
print('Result of inplace operation: '+str(a))

tensor([1, 2]) + tensor([16, 16]) = tensor([17, 18])
Result of inplace operation: tensor([17, 18])


In [51]:
# indexing elements from a tensor
a = torch.randint(10,(2,4))
print(a)
print(a[1,:]) # select the 2nd row
print(a[:,1]) # select the 2nd column
print(a[1,3]) # select a specific element
print(a[1,3].item()) # use .item method to get the content of a single element tensor
print(a.detach().numpy()) # to get content of a multi-element/ dimensional tensor

tensor([[8, 6, 5, 2],
        [6, 6, 8, 2]])
tensor([6, 6, 8, 2])
tensor([6, 6])
tensor(2)
2
[[8 6 5 2]
 [6 6 8 2]]


In [56]:
# Reshaping tensors using view() method
b = torch.randint(10,(2,4)) 
print("\n b: %s \n b.view(8): %s \n b.view(-1,6): %s" %(b, b.view(8), b.view(-1,4)))



 b: tensor([[4, 5, 9, 6],
        [9, 0, 4, 0]]) 
 b.view(8): tensor([4, 5, 9, 6, 9, 0, 4, 0]) 
 b.view(-1,6): tensor([[4, 5, 9, 6],
        [9, 0, 4, 0]])


In [62]:
# Intro to Autograd:

# Autograd: performs automatic differentiation in Pytorch.
# For model training we work with two passes through the Neural Network: 
# 1) The forward pass: predicts about the target label, based on its current network weights.
# 2) Backward pass: propagates the difference between the target and predicted labels(the error) backward through the network.
#    It collects the derivatives of the error w.r.t. the parameters of the functions (gradients), and optimizing the parameters using gradient descent.


In [89]:
# To enable autograd tracking we need to set 'requires_grad' flag to 'True' for each tensor.
a = torch.tensor([2.,4.], requires_grad = True)
b = torch.tensor([6.,9.], requires_grad = True)

# Assuming a and b be parameters of the NN and Q be the error
Q = 9*a**3 - b**2

# in NN learning we need to take the gradient of error w.r.t the parameters i.e. dQ/da and dQ/db
external_grad = torch.tensor([1., 1.])
Q.backward(gradient=external_grad)

print(27*a**2 == a.grad) #Check if correct

tensor([108., 432.], grad_fn=<MulBackward0>)
